"""
===============================================================================
File: response_parser.py

Purpose:
    Provides utility functions for cleaning, validating, and parsing JSON
    responses generated by Large Language Models (LLMs).

Functions:
    strip_markdown(text)
        Removes Markdown code block formatting (e.g., ```json ... ```)
        from LLM responses and returns the cleaned text.

    parse_response(text)
        Cleans an LLM response, deserializes the JSON content into Python
        objects, and simplifies single-item lists when appropriate.

Author:
    Souroosh Memarian

Created:
    2026-07-21

Last Modified:
    2026-07-21

Notes:
    - Supports JSON responses wrapped in Markdown code fences.
    - Handles both ```json and generic ``` code blocks.
    - Converts valid JSON strings into native Python objects.
    - Single-element JSON arrays are automatically unwrapped to reduce
      unnecessary nesting.
    - Raises json.JSONDecodeError if the cleaned response is not valid JSON.

===============================================================================
"""

import json


def strip_markdown(text):

    text = text.strip()

    if text.startswith("```json"):
        text = text[7:]

    elif text.startswith("```"):
        text = text[3:]

    if text.endswith("```"):
        text = text[:-3]

    return text.strip()


def parse_response(text):

    cleaned = strip_markdown(text)

    parsed = json.loads(cleaned)

    if (
        isinstance(parsed, list)
        and len(parsed) == 1
    ):
        return parsed[0]

    return parsed